#!/bin/sh -e

# LTO is broken.
export CFLAGS="${BASE_FLAGS}"
export CXXFLAGS="${BASE_FLAGS}"
export LDFLAGS="${BASE_LDFLAGS}"

# Remove the perl requirement from configure.
# Also fix issue with non-GNU diff.
sed -i 's/perl/:/g;s/diff --version/command -v diff/' configure

./configure \
	--prefix=/usr \
	--target=x86_64-linux-gcc \
	--enable-vp8 \
	--enable-vp9 \
	--enable-experimental \
	--enable-runtime-cpu-detect \
	--enable-shared \
	--enable-postproc \
	--enable-pic \
	--disable-tools \
	--disable-examples \
	--disable-docs \
	--disable-unit-tests \
	--disable-install-docs \
	--disable-install-srcs \
	--disable-install-bins \
	--as=nasm

gmake
gmake install
