#!/bin/sh -e

sed -i '/chown/d' GNUmakefile

./configure \
	--prefix=/usr \
	--with-shadow \
	--with-timestamp \
	--without-pam

gmake
gmake install

mkdir -p "$1/etc"
cp -f doas.conf "$1/etc"
chmod 600 "$1/etc/doas.conf"
