#!/bin/sh -e

./configure \
	--prefix=/usr \
	--sysconfdir=/etc

make
make install

# Remove man pages.
rm -rf "$1/usr/share/man"

# Install the certificate database.
cd "$1/etc/ssl"

curl -LO https://curl.haxx.se/ca/cacert.pem
mv cacert.pem cert.pem
