#!/bin/sh -e

# Move 'osc.lua' to the right location.
mv -f osc.lua player/lua

python waf/waf configure \
	--prefix=/usr \
	--mandir=/usr/share/man \
	--confdir=/etc/mpv \
	--enable-alsa \
	--enable-wayland \
	--disable-x11 \
	--lua="luajit"

python waf/waf build
python waf/waf install --destdir="$1"

rm -rf \
	"$1/usr/share/zsh" \
	"$1/usr/share/bash-completion"
