#!/bin/sh -e

meson \
	--prefix=/usr \
	--buildtype=release \
	--force-fallback-for=fcft,tllist \
	-Dterminfo=disabled \
	-Ddocs=disabled \
	. output

ninja -C output
ninja -C output install

# $1 can never be non-existent.
# shellcheck disable=2115
rm -rf "$1/usr/share"
