#!/bin/sh -e

# Disable documentation (READMEs and such).
sed -i 's/^\(dist_doc_DATA\)/\1_null/' Makefile.in

./configure \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--mandir=/usr/share/man \
	--disable-compat-symlinks

make
make install
