#!/bin/sh -e

make CC="${CC} ${CFLAGS} -fPIC ${LDFLAGS}" -f Makefile-libbz2_so
make CC="${CC} ${CFLAGS} -fPIC ${LDFLAGS}" bzip2

mkdir -p \
	"$1/usr/bin" \
	"$1/usr/lib" \
	"$1/usr/share/man/man1" \
	"$1/usr/include"

# Make "bzmore" executable.
chmod +x bzmore

# Copy the binaries.
cp -f \
	bzip2 \
	bzdiff \
	bzgrep \
	bzmore \
	"$1/usr/bin"

# Copy the libraries.
cp -f \
	libbz2.so.1.0.8 \
	libbz2.a \
	"$1/usr/lib"

# Copy the headers.
cp -f bzip2.1          "$1/usr/share/man/man1"
cp -f bzlib.h          "$1/usr/include"

# Symlink the libraries.
ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so"
ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1"
ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1.0"

# Symlink the binaries.
ln -sf bzip2           "$1/usr/bin/bunzip2"
ln -sf bzip2           "$1/usr/bin/bzcat"
