#!/bin/sh -e

# LTO is broken.
export CFLAGS="${CFLAGS%%-flto=thin}"
export CXXFLAGS="${CXXFLAGS%%-flto=thin}"
export LDFLAGS="${LDFLAGS%%-flto=thin}"

# Remove libatomic dependency.
sed -i 's/-latomic//' node.gyp

./configure \
	--shared-zlib \
	--with-intl=none \
	--without-etw \
	--without-dtrace \
	--without-report \
	--without-node-snapshot \
	--without-node-code-cache \
	--ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded files.
rm -rf \
	"$1/usr/include/node/openssl" \
	"$1/usr/share/doc" \
	"$1/usr/share/systemtap" \
	"$1/usr/lib/node_modules/npm/scripts" \
	"$1/usr/lib/node_modules/npm/configure"
