#!/bin/sh -e

patch -p1 < portability.patch

# LTO is broken.
export CFLAGS="${CFLAGS%%-flto=thin}"

./configure \
	--prefix=/usr \
	--disable-swscale \
	--enable-pic \
	--enable-shared

gmake
gmake install
