#!/bin/sh -e
# shellcheck disable=2016

# Fix alsamixer for netbsd-curses.
sed -i -e 's/ MIN_MENU_COMMAND/REQ_LEFT_ITEM/' \
	-e 's/ MAX_MENU_COMMAND/REQ_PREV_MATCH/' \
	alsamixer/bindings.h

# Fix the Makefile.
sed -i '/\$(edit)\|\.\(service\|rules\)/d' alsactl/Makefile.in
sed -i '/\$(edit)\|\.\(service\|rules\)/d' alsaucm/Makefile.in

./configure \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--disable-alsaconf \
	--disable-bat \
	--disable-xmlto \
	--disable-nls

make
make install
